name: Build Beacon Audio RC

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v4

    - name: Configuration de .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Compilation de l'exécutable autonome
      run: dotnet publish BeaconAudioRC/BeaconAudioRC.csproj -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true -o output

    - name: Sauvegarde de l'exécutable (.exe)
      uses: actions/upload-artifact@v4
      with:
        name: BeaconAudioRC-Windows-EXE
        path: output/BeaconAudioRC.exe
